# Generated by Django 5.2.11 on 2026-06-22 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.CharField(help_text='例: 00, 01, 12（文字列で管理）', max_length=10, unique=True, verbose_name='章番号')),
                ('title', models.CharField(max_length=200, verbose_name='章タイトル')),
                ('estimated_days', models.PositiveIntegerField(default=0, help_text='アラート判定・完了予定日の自動算出に使用', verbose_name='想定日数')),
                ('display_order', models.PositiveIntegerField(verbose_name='表示順')),
            ],
            options={
                'verbose_name': 'カリキュラム章',
                'verbose_name_plural': 'カリキュラム章一覧',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(help_text='例: 01, 02, 00-1, 00-2', max_length=10, verbose_name='項目番号')),
                ('title', models.CharField(max_length=200, verbose_name='項目名')),
                ('display_order', models.PositiveIntegerField(verbose_name='表示順')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='trainee_management.curriculumchapter', verbose_name='章')),
            ],
            options={
                'verbose_name': 'カリキュラム小項目',
                'verbose_name_plural': 'カリキュラム小項目一覧',
                'ordering': ['chapter__display_order', 'display_order'],
                'unique_together': {('chapter', 'item_number')},
            },
        ),
        migrations.CreateModel(
            name='TraineeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', '未受講'), ('in_progress', '受講中'), ('completed', '完了')], default='not_started', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, help_text='ステータスを「受講中」に変更する際に手動入力する', null=True, verbose_name='学習開始日')),
                ('expected_completion_date', models.DateField(blank=True, help_text='学習開始日 + 全章の想定日数合計（90日）で自動算出', null=True, verbose_name='完了予定日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, help_text='主なフォロー担当の連絡窓口。閲覧権限はすべての講師に付与されるため、アクセス制限の意味は持たない', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentees', to=settings.AUTH_USER_MODEL, verbose_name='担当メンバー')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profile', to=settings.AUTH_USER_MODEL, verbose_name='受講生ユーザー')),
            ],
            options={
                'verbose_name': '受講生プロフィール',
                'verbose_name_plural': '受講生プロフィール一覧',
            },
        ),
        migrations.CreateModel(
            name='ItemProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_minutes', models.PositiveIntegerField(default=0, help_text='study_recordsから集計したキャッシュ値', verbose_name='累計学習時間（分）')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresses', to='trainee_management.curriculumitem', verbose_name='カリキュラム小項目')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_progresses', to='trainee_management.traineeprofile', verbose_name='受講生')),
            ],
            options={
                'verbose_name': '小項目別学習時間',
                'verbose_name_plural': '小項目別学習時間一覧',
                'unique_together': {('trainee', 'curriculum_item')},
            },
        ),
        migrations.CreateModel(
            name='ChapterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了フラグ')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('total_minutes', models.PositiveIntegerField(default=0, help_text='study_recordsから集計したキャッシュ値。study_record保存時に自動更新される', verbose_name='累計学習時間（分）')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progresses', to='trainee_management.curriculumchapter', verbose_name='章')),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_progresses', to='trainee_management.traineeprofile', verbose_name='受講生')),
            ],
            options={
                'verbose_name': '章別進捗',
                'verbose_name_plural': '章別進捗一覧',
                'unique_together': {('trainee', 'chapter')},
            },
        ),
    ]
