# Generated by Django 5.2.11 on 2026-06-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_seed_curriculum_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='is_curriculum',
            field=models.BooleanField(default=False, help_text='管理ダッシュボードのカリキュラム機能と紐づく学習記録かどうか', verbose_name='カリキュラム学習記録'),
        ),
    ]
