# Generated by Django 5.2.11 on 2026-06-22 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_studyrecord_is_curriculum'),
        ('trainee_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='curriculum_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_records', to='trainee_management.curriculumchapter', verbose_name='カリキュラム章'),
        ),
        migrations.AddField(
            model_name='studyrecord',
            name='curriculum_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_records', to='trainee_management.curriculumitem', verbose_name='カリキュラム小項目'),
        ),
    ]
